### ISSUE TITLE
Cannot run DotNetToJScript.exe

### ISSUE THREAD

**Issue by Crankle437** [tyranid/DotNetToJScript#18]
Not able to run DotNetToJScript.exe and create Jscript. I've install .NET v2.0:

```
PS> $PSVersionTable

Name                           Value
----                           -----
CLRVersion                     2.0.50727.9151
BuildVersion                   6.1.7600.16385
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1
PS > .\DotNetToJScript.exe
This tool should only be run on v2 of the CLR
```

OS Version:                10.0.18363 N/A Build 18363

**Comment by raulmozosuarez** [comment]
Hi @Crankle437 could you please let me know how did you fix it? thanks

**Comment by GianRathgeb** [comment]
Hi @raulmozosuarez 

I had the same issue, could solve it by using the debug version of DotNetToJscript. 
It should be located in PATH\DotNetToJScript-master\DotNetToJScript\bin\Debug\DotNetToJScript.exe.

Hope that future readers can solve the issue with that solution.
