### ISSUE TITLE
Vb net 

### ISSUE THREAD

**Issue by H1-N1** [tyranid/DotNetToJScript#2]
hi 

testing this amazing tool with Vb .net assembly 
 it loads in memory then the wscipt close directly :/

**Comment by tyranid** [comment]
You need to make sure that the class name in the VB assembly matches the one used in the tool including the additional namespace. The default is TestClass. The most likely reason is that in VB library a root namespace is created (which you don't see in the code). If you've using VisualStudio then look in the project properties for the root namespace. E.g. if the root namespace is VbLibrary then pass the the parameters '-c VbLibrary.TestClass'. I might add support to check that the name you specify really exists.

**Comment by tyranid** [comment]
Added support to the tool to print out available classes if the specified one doesn't match so that you can correct your command line. Get it from https://github.com/tyranid/DotNetToJScript/releases/tag/v1.0.1
