### ISSUE TITLE
RFI: assembly which targets .NET 2

### ISSUE THREAD

**Issue by Arno0x** [tyranid/DotNetToJScript#6]
Hi,

Thank you for sharing this excellent tool and method.

This is not an issue but rather a Request For Information.

Could you please elaborate on why is it required to create an assembly which targets .NET2 and not let's say .NET4 ?

Actually if you have a paper or something explaining the nifty details of how all this works could you point me to it ?

Thanks,
Arno

**Comment by tyranid** [comment]
It will work with v4 assemblies, but you need to ensure you enable the version with either -ver 4 or -ver auto flags when building the javascript file. If you want some information about how it works checkout https://github.com/tyranid/DotNetInteropDemos/releases/download/DERBYCON_2017/NET.Interop.Slides.pdf which is a presentation I did on it (towards) then end.

**Comment by Arno0x** [comment]
Fantastic, thank you very much !
